const illustrations: Record<string, string> = {
  asobu: '⚽', abiru: '🚿', arau: '🧼', utau: '🎤', okiru: '⏰', oyogu: '🏊',
  kaburu: '👒', kiru: '👕', suu: '🚬', sumu: '🏠', suwaru: '🪑', tanoshimu: '😊',
  taberu: '🍱', tsuru: '🎣', nugu: '🔓', neru: '😴', nomu: '🍶', haku: '👟',
  migaku: '🦷', yasumu: '☕', agaru: '⬆️', aruku: '🚶', iku: '➡️', oriru: '⬇️',
  kaeru: '↩️', kuru: '⬇️', sagaru: '🔽', susumu: '⏭️', tatsu: '🧍', tsuku: '🛬',
  dekakeru: '🚪', deru: '🚪', tobu: '✈️', tomaru: '⏸️', tooru: '🔁', nigeru: '💨',
  noboru: '🧗', noru: '🚆', hairu: '🚪', hashiru: '🏃', hikkosu: '📦', fumu: '👣',
  magaru: '🔄', mawaru: '🔁', mukau: '👋', modoru: '↩️', wataru: '🌉',
  au: '🤝', aku: '🔓', aru: '📍', iru: '📍', umareru: '👶', owaru: '🏁',
  kakaru: '💰', kieru: '👻', kureru: '🌆', komaru: '😰', komu: '🚇', kowareru: '💥',
  saku: '🌸', shinu: '⚰️', shimaru: '🔒', sodatsu: '🌱', sugiru: '⌛', sumu: '✅',
  suberu: '🌨️', taoreru: '💥', tariru: '✓', chigau: '❌', tsukareru: '😩',
  tsukamaru: '🚫', tsuzuku: '➡️', dekiru: '✅', todoku: '📬', naku: '🐦',
  nakunaru: '⚰️', narabu: '🚶', naru: '🔄', naoru: '💊', nareru: '😌', niru: '👥',
  nureru: '🌧️', nokoru: '🎁', hajimaru: '🚀', hareru: '☀️', hieru: '❄️',
  hikaru: '✨', hiraku: '📖', fuku: '💨', fueru: '➕', futoru: '🍔', furu: '🌧️',
  makeru: '😞', maniau: '⏰', mitsukaru: '🔍', yakunitatsu: '🔧', yaseru: '🥗',
  waku: '♨️', wareru: '🥧',
  ou: '🤝', oku: '📥', ireru: '📤', oku: '📍', suku: '🌱', shinu: '⚰️',
  shimaru: '🔒', sodatsu: '🌿', sugiru: '⏩', sumu: '✅',
  suberu: '🌨️', taoreru: '💥', tariru: '✓', chigau: '❌', tsukareru: '😩',
  tsukamaru: '🚫', tsuzuku: '➡️', dekiru: '✅', todoku: '📬', naku: '🐦',
  nakunaru: '⚰️', narabu: '🚶', naru: '🔄', naoru: '💊', nareru: '😌', niru: '👥',
  nureru: '🌧️', nokoru: '🎁', hajimaru: '🚀', hareru: '☀️', hieru: '❄️',
  hikaru: '✨', hiraku: '📖', fuku: '💨', fueru: '➕', futoru: '🍔', furu: '🌧️',
  makeru: '😞', maniau: '⏰', mitsukaru: '🔍', yakunitatsu: '🔧', yaseru: '🥗',
  waku: '♨️', wareru: '🥧',
  oboreru: '🧠', kaku: '✍️', kimaru: '🔔', kimeru: '✅', kuraberu: '⚖️',
  shiraberu: '🕵️', shiru: '🧠', sodateru: '👶', tasu: '➕', tsukau: '🤲',
  tsukuru: '🔨', tsutomeru: '💼', hataraku: '💼', machigaeru: '❌', yameru: '🛑',
  yomu: '📖', wakaru: '💡', wasureru: '🤔', oboeru: '🧠', kaku: '✍️',
  sodateru: '👶', tasu: '➕', tsukau: '🤲', tsukuru: '🔨', tsutomeru: '💼',
  hataraku: '💼', machigaeru: '❌', yameru: '🛑', yomu: '📖', wakaru: '💡',
  wasureru: '🤔',
  ageru: '🆙', uru: '💰', okuru: '📤', kau: '💸', kaesu: '🔙', kasu: '🤝',
  kariru: '🤝', kureru: '📥', torikaeru: '🔄', harau: '💵', morau: '📥',
  watasu: '📤',
  akeru: '🔓', ireru: '📤', oku: '📥', osu: '✊', kakeru: '🎯', kiru: '✂️',
  kesu: '🗑️', kowasu: '💥', sageru: '🔽', sasu: '☝️', sawaru: '✋', shimeru: '🔒',
  suteru: '🗑️', suru: '🔧', dasu: '📤', tateru: '🏗️', tsukamaeru: '✋',
  tsukeru: '🔌', tsutsumu: '🎁', tomeru: '⏸️', toru: '✋', todokeru: '📬',
  naraberu: '🧺', naosu: '💊', nageru: '➡️', nusumu: '🙈', nuru: '🎨', hakobu: '📦',
  haru: '📌', hiku: '⬇️', hikidasu: '⬆️', hirou: '✋', mitsukeru: '🔍',
  miru: '👁️', motsu: '✊', yaku: '🔥', yaru: '🔧', wakasu: '♨️', waru: '➕',
  ageru: '🆙', uru: '💰', okuru: '📤', kau: '💸', kaesu: '🔙', kasu: '🤝',
  kariru: '🤝', kureru: '📥', torikaeru: '🔄', harau: '💵', morau: '📥',
  au: '🤝', aku: '🔓', aru: '📍', iru: '📍', umareru: '👶', owaru: '🏁',
  kakaru: '💰', kieru: '👻', kureru: '🌆', komaru: '😰', komu: '🚇', kowareru: '💥',
  saku: '🌸', shinu: '⚰️', shimaru: '🔒', sodatsu: '🌱', sugiru: '⌛', sumu: '✅',
  suberu: '🌨️', taoreru: '💥', tariru: '✓', chigau: '❌', tsukareru: '😩',
  tsukamaru: '🚫', tsuzuku: '➡️', dekiru: '✅', todoku: '📬', naku: '🐦',
  nakunaru: '⚰️', narabu: '🚶', naru: '🔄', naoru: '💊', nareru: '😌', niru: '👥',
  nureru: '🌧️', nokoru: '🎁', hajimaru: '🚀', hareru: '☀️', hieru: '❄️',
  hikaru: '✨', hiraku: '📖', fuku: '💨', fueru: '➕', futoru: '🍔', furu: '🌧️',
  makeru: '😞', maniau: '⏰', mitsukaru: '🔍', yakunitatsu: '🔧', yaseru: '🥗',
  waku: '♨️', wareru: '🥧',
  ou: '🤝', oku: '🔽', iru: '📍', umareru: '👶', owaru: '🏁',
  kakaru: '💰', kieru: '👻', komaru: '😰', komu: '🚇', kowareru: '💥',
  saku: '🌸', shinu: '⚰️', shimaru: '🔒', sodatsu: '🌱', sugiru: '⌛', sumu: '✅',
  suberu: '🌨️', taoreru: '💥', tariru: '✓', chigau: '❌', tsukareru: '😩',
  tsukamaru: '🚫', tsuzuku: '➡️', dekiru: '✅', todoku: '📬', naku: '🐦',
  nakunaru: '⚰️', narabu: '🚶', naru: '🔄', naoru: '💊', nareru: '😌', niru: '👥',
  nureru: '🌧️', nokoru: '🎁', hajimaru: '🚀', hareru: '☀️', hieru: '❄️',
  hikaru: '✨', hiraku: '📖', fuku: '💨', fueru: '➕', futoru: '🍔', furu: '🌧️',
  makeru: '😞', maniau: '⏰', mitsukaru: '🔍', yakunitatsu: '🔧', yaseru: '🥗',
  waku: '♨️', wareru: '🥧', sashiageru: '🆙', meshiagaru: '🍽️', moushiageru: '🙇',
  mousu: '🙏', au: '🤝'
};

export const getIllustration = (romaji: string): string | null => {
  const normalized = romaji.toLowerCase().replace(/[^a-z]/g, '');
  return illustrations[normalized] || null;
};

export const getThemeIllustration = (themeName: string): string | null => {
  const themes: Record<string, string> = {
    'Aktivitas Sehari-hari & Kebutuhan Dasar': '🏠',
    'Pergerakan, Arah & Transportasi': '🚗',
    'Komunikasi & Interaksi Sosial': '🗣️',
    'Pekerjaan, Belajar & Aktivitas Kognitif': '💼',
    'Transaksi, Kepemilikan & Perpindahan Barang': '💳',
    'Tindakan Fisik & Manipulasi Objek': '🤲',
    'Kondisi, Keadaan, Perubahan & Alam': '🌦️',
    'Bahasa Hormat (Keigo)': '🙏',
  };
  return themes[themeName] || null;
};